export type { IComponent, ExcelComponentOptions } from './model/types/core'
export { ExcelComponent } from './ExcelComponent'
export { DomListener } from './DomListener'
export { $ } from './lib/dom'
export type { DomElement } from './lib/dom'
